version: '3.8'

services:
  db:
    build:
      context: ./db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    build:
      context: ./app
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - db

networks:
  app_network:

volumes:
  db_data:
