name: deploy-docker-db

on:
  push:
    branches:
      - docker

jobs:
  deploy:
    name: Deploy MySQL container to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Docker container
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if ! command -v docker &> /dev/null
            then
                echo "Docker not found, installing..."
                sudo apt update
                sudo apt install -y docker.io
            fi

            if [ "$(docker ps -aq -f name=mysql-container)" ]; then
                echo "Removing existing MySQL container..."
                docker stop mysql-container
                docker rm mysql-container
            fi

            echo "Starting MySQL container..."
            docker run -d \
                --name mysql-container \
                -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} \
                -e MYSQL_DATABASE=mydb \
                -e MYSQL_USER=myuser \
                -e MYSQL_PASSWORD=mypassword \
                -p 3306:3306 \
                mysql:8.0
